header_text = "Всякие разности"

[author]
fn = "Alexander Kharchenko"
bio = "Физик, математик и программист"
email = "morontt@yandex.ru"
github = "morontt"
telegram = "xelbotcom"
mastodon = "https://mastodon.online/@morontt"

[author_location]
city    = "Симферополь"
region  = "Республика Крым"
country = "Россия"

[author_location_en]
city    = "Simferopol"
region  = "Republic of Crimea"
country = "Russia"

[[jobs]]
company = "Lazy-Ants"
link = "https://lazy-ants.de/"
title = "Senior PHP Developer"
start = 2011-07-01
end = 2016-08-31

[[jobs]]
company = "Zfort Group"
link = "https://www.zfort.com/"
title = "Software Developer"
start = 2016-09-01
end = 2019-07-01

[[jobs]]
company = "Brander"
link = "https://brander.ua/"
title = "Senior PHP Developer"
start = 2019-09-01
end = 2020-06-01

[[jobs]]
company = "AutoDoc"
link = "https://www.autodoc.eu/"
title = "Senior PHP Developer"
start = 2020-07-01
end = 2022-12-12

[[jobs]]
company = "Элакс"
title = "Electrical Engineer"
start = 2007-12-01
end = 2009-09-01
emoji = "electrical"

[[jobs]]
company = "VK"
link = "https://team.vk.company/"
title = "Разработчик"
start = 2024-06-25
end = 2099-01-01
