version: "3.5"
services:
    source:
        build:
            context: .
            dockerfile: "docker/app/Dockerfile"
        container_name: "gopher"
        volumes:
            - ./:/var/www/app
        ports:
            - "8044:8080"
        networks:
            - blognet

networks:
    blognet:
        external: true
