version: "3.5"
services:
    source:
        build:
            context: .
            dockerfile: "docker/app/Dockerfile"
        container_name: "gopher"
        volumes:
            - ./:/var/www/app
        ports:
            - "8044:8080"
        networks:
            - blognet

    varnish:
        image: varnish:7.0-alpine
        container_name: "reprogl_varnish"
        volumes:
            - ./docker/varnish/default.vcl:/etc/varnish/default.vcl:ro
        tmpfs:
            - /var/lib/varnish:exec
        ports:
            - "8086:80"
        links:
            - source
        depends_on:
            - source
        networks:
            - blognet

    nodejs:
        build: ./docker/nodejs
        volumes:
            - ./:/var/www/app

networks:
    blognet:
        external: true
