version: "2"
services:
    source:
        build:
            context: .
            dockerfile: "docker/app/Dockerfile"
        volumes:
            - ./:/var/www/app
    nginx:
        build: ./docker/nginx
        ports:
            - "80:80"
            - "443:443"
        depends_on:
            - source
        volumes_from:
            - source
        links:
            - source
