services:
    gopher:
        build:
            context: .
            dockerfile: "docker/app/Dockerfile"
        platform: linux/amd64
        container_name: "gopher"
        volumes:
            - ./:/var/www/app
        ports:
            - "8044:8080"
        extra_hosts:
            - "database.lan:${DATABASE_IP}"
            - "zendblog.xelbot.com:${APPLICATION_IP}"
        networks:
            - blognet

    varnish:
        image: varnish:7.2-alpine
        platform: linux/amd64
        container_name: "reprogl_varnish"
        environment:
            BAN_TOKEN: ${BAN_TOKEN}
        volumes:
            - ./docker/varnish/default.vcl:/etc/varnish/default.vcl:ro
        tmpfs:
            - /var/lib/varnish:exec,uid=100,gid=101
        ports:
            - "8086:80"
        links:
            - gopher
        depends_on:
            - gopher
        networks:
            - blognet

    prometheus:
        image: prom/prometheus
        platform: linux/amd64
        container_name: "reprogl_prometheus"
        volumes:
            - ./docker/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
            - prometheus-data:/prometheus
        ports:
            - "9090:9090"
        links:
            - gopher
        depends_on:
            - gopher
        networks:
            - blognet

    grafana:
        image: grafana/grafana:11.3.1
        ports:
            - "3000:3000"
        environment:
            - GF_SECURITY_ADMIN_USER=admin
            - GF_SECURITY_ADMIN_PASSWORD=admin123
        volumes:
            - ./docker/grafana/datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml
            - grafana:/var/lib/grafana
        links:
            - prometheus
        depends_on:
            - prometheus
        networks:
            - blognet

networks:
    blognet:
        external: true

volumes:
    prometheus-data:
    grafana:
