[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  name = "github.com/gorilla/mux"
  version = "1.7.1"

[[constraint]]
  name = "github.com/gookit/ini"
  version = "2.0.0"

[[constraint]]
  name = "github.com/CloudyKit/jet"
  version = "2.1.2"
