#!/usr/bin/env bash

echo -e "\033[36mStart pre-push hook\033[0m\n"

./test.sh

retVal=$?
if [ $retVal -ne 0 ]; then
    echo -e "\n\033[1;31mgo test error\033[0m\n"
    exit 1
else
    echo -e "\n\033[1;32mgo test OK\033[0m\n"
fi

exit 0
