#!/usr/bin/env bash

echo -e "\033[36mStart pre-push hook\033[0m\n"

LDFLAGS="-X 'xelbot.com/reprogl/container.BuildTime=$(date -u +"%a, %d %b %Y %H:%M:%S %Z")'"
LDFLAGS="$LDFLAGS -X 'xelbot.com/reprogl/container.Version=9.9.9'"
LDFLAGS="$LDFLAGS -X 'xelbot.com/reprogl/container.GitRevision=f0f0f0'"

./test.sh

retVal=$?
if [ $retVal -ne 0 ]; then
    echo -e "\n\033[1;31mgo test error\033[0m\n"
    exit 1
else
    echo -e "\n\033[1;32mgo test OK\033[0m\n"
fi

exit 0
